In [7]:
import pandas as pd

# **Prueba #2**
En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github antes de el domingo 18 de Febrero a las 23:59:59.

## **Ejercicio 1** (40%)

Construya un DataFrame a partir del siguiente diccionario

`exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}`

con las siguientes etiquetas para los índices

`labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']`

1. Seleccione solo las columnas *name* y *score*.
  
2. Filtre las filas donde el número de intentos (attemps) sea mayor que 2.

3. Filtre las filas donde el *score* se encuentre entre 15 y 20 (incluidos)

4. Cambie el *score* en la fila 'd' a 11.5

5. Agregue una nueva fila con etiqueta 'k' al dataframe con un valor que usted desee para cada columna

6. Borre la fila 'k' y entregue nuevamente el DataFrame original.

7. Ordene el DataFrame por nombre en orden ascendente.

8. Reemplace los valores de la columna *qualify* que contiene los valores *yes* y *no* por los valores booleanos True y False respectivamente.

In [ ]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 
             'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data, index=labels)
df

In [ ]:
#1
df[['name','score']]

In [ ]:
#2
df[df['attempts']>2]

In [ ]:
#3
df[(df['score']>=15) & (df['score']<=20)]

In [ ]:
#4
df.loc[df.index=='d', 'score'] = 11.5
df

In [ ]:
#5
df['k']='New Value'
df

In [ ]:
#6
df.drop('k', axis=1, inplace=True)
df

In [ ]:
#7
df.sort_values(by=['name'], ascending=True)

In [ ]:
#8
df['qualify'] = df['qualify'].replace({'yes': True, 'no': False})
df

## **Ejercicio 2** (30%)

Importe el dataset `athletes` del repositorio del curso y realice las siguientes tareas:

1. Importarlo como nombre athletes
2. Filtre el dataframe tal que solo se quede con los atletas que hayan ganado al menos una medalla.
3. Calcule la masa muscular por fila con una función como

$$I_{m.m.} = \frac{Weight}{Height^2}$$

4. Agrupe los datos por calculando la media por deporte para cada una del resto de características. ¿Cuál es el deporte en el que los jugadores tienen mayor peso promedio?

5. ¿Cuál es el pais con más participación femenina?

In [83]:
#1
athletes = pd.read_csv("https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/athletes.csv")

In [84]:
#2
athletes = athletes.loc[(athletes.gold > 0) | (athletes.silver > 0) | (athletes.bronze > 0)]
athletes

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1
14,162792594,Abbey Weitzeil,USA,female,12/3/96,1.78,68.0,aquatics,1,1,0
48,962468808,Abdoulrazak Issoufou Alfaga,NIG,male,12/26/94,2.07,98.0,taekwondo,0,1,0
55,969824503,Abdullah Alrashidi,IOA,male,8/21/63,1.83,84.0,shooting,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
11487,334126873,Zhiyong Shi,CHN,male,10/10/93,1.68,69.0,weightlifting,1,0,0
11491,105609876,Zi He,CHN,female,12/10/90,1.60,52.0,aquatics,0,1,0
11503,593183472,Zivko Gocic,SRB,male,8/22/82,1.93,93.0,aquatics,1,0,0
11509,836633838,Zoe Lee,GBR,female,12/15/85,1.76,70.0,rowing,0,1,0
11511,343671816,Zoe de Toledo,GBR,female,7/17/87,1.72,58.0,rowing,0,1,0

In [85]:
#3
athletes["IMM"] = athletes.weight / athletes.height.pow(2)
athletes

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,IMM
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1,20.151005
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1,23.319453
14,162792594,Abbey Weitzeil,USA,female,12/3/96,1.78,68.0,aquatics,1,1,0,21.461937
48,962468808,Abdoulrazak Issoufou Alfaga,NIG,male,12/26/94,2.07,98.0,taekwondo,0,1,0,22.871012
55,969824503,Abdullah Alrashidi,IOA,male,8/21/63,1.83,84.0,shooting,0,0,1,25.082863
...,...,...,...,...,...,...,...,...,...,...,...,...
11487,334126873,Zhiyong Shi,CHN,male,10/10/93,1.68,69.0,weightlifting,1,0,0,24.447279
11491,105609876,Zi He,CHN,female,12/10/90,1.60,52.0,aquatics,0,1,0,20.312500
11503,593183472,Zivko Gocic,SRB,male,8/22/82,1.93,93.0,aquatics,1,0,0,24.967113
11509,836633838,Zoe Lee,GBR,female,12/15/85,1.76,70.0,rowing,0,1,0,22.598140
11511,343671816,Zoe de Toledo,GBR,female,7/17/87,1.72,58.0,rowing,0,1,0,19.605192

In [119]:
#4
a = athletes.groupby('sport').mean(numeric_only=True).sort_values(["weight"],ascending=False).head()
display(a)
print(f"los de {a.index[0]} son los mas pesados en promedio")

los de basketball son los mas pesados en promedio

,id,height,weight,gold,silver,bronze,IMM
sport,,,,,,,
basketball,4.855873e+08,1.929861,87.527778,0.333333,0.333333,0.333333,23.264874
handball,4.694044e+08,1.850000,86.027027,0.329545,0.340909,0.329545,24.399223
volleyball,4.460279e+08,1.926386,82.277108,0.337349,0.325301,0.337349,22.090778
rowing,5.354096e+08,1.857643,81.678571,0.333333,0.333333,0.333333,23.483324
rugby sevens,5.085589e+08,1.765946,81.256757,0.337838,0.324324,0.337838,25.869383

In [108]:
#5
b = athletes.loc[athletes.sex == "female"].groupby(["nationality"])["name"].count().sort_values(0,ascending=False)
display(b)
print(f"la Mayor participacion fue {b.index[0]}")

<ipython-input-108-a8bc2fc65d13>:1: FutureWarning: In a future version of pandas all arguments of Series.sort_values will be keyword-only.
  b = athletes.loc[athletes.sex == "female"].groupby(["nationality"])["name"].count().sort_values(0,ascending=False)

nationality
USA    117
RUS     74
CHN     68
GER     63
GBR     59
      ...
BDI      1
TUR      1
BAH      1
AUT      1
MGL      1
Name: name, Length: 66, dtype: int64

la Mayor participacion fue USA

## **Ejercicio 3 (30%)**

Importe el dataset de nba del repositorio de clase y responda (hint: Elimine las instancias con registros faltantes):

1. Cuáles son los equipos que pagan los salarios más altos (presente el resultado como un dataFrame con el nombre del equipo y la cantidad de dinero de la nómina)
2. Separe la variable *Age* en tres grupos y cree una nueva columna llamada *Age-Group* con esta información.<
3. Construya una tabla dinámica que muestre el salario promedio de los jugadores por equipo y posición para para los cinco equipos que pagan mejores salarios.